### ISSUE TITLE
Missing API

### ISSUE THREAD

**Issue by paulpdaniels** [Dapperware/zio-slack#9]
These APIs are still missing:

- [ ] Admin Apps
- [ ] Admin Conversations
- [ ] Admin Invite Requests
- [ ] Admin Teams
- [ ] Admin Users
- [ ] Apps Permissions
- [X] Apps
- [ ] Bots
- [X] OAuth
- [X] OAuthV2
- [ ] Pins
- [ ] Team APIs
- [ ] New User APIs
- [ ] Files remote api
- [ ] Files comments delete

**Comment by ashwinbhaskar** [comment]
I can pick up `pins.add` (https://api.slack.com/methods/pins.add)

**Comment by ashwinbhaskar** [comment]
I can pick up `file.remote.add` https://api.slack.com/methods/files.remote.add
